# Generated by Django 3.1.2 on 2020-10-27 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=500)),
                ('rating', models.CharField(choices=[('5', '5/5'), ('4', '4/5'), ('3', '3/5'), ('2', '2/5'), ('1', '1/5'), ('0', '0/5')], default='5', max_length=1)),
                ('vinyl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vinyl')),
            ],
        ),
    ]
