# Generated by Django 3.1.2 on 2020-10-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=100)),
                ('season', models.CharField(choices=[('winter', 'Winter'), ('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall')], default='winter', max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='vinyl',
            name='moods',
            field=models.ManyToManyField(to='main_app.Mood'),
        ),
    ]
